---
- name: Check if uninstall script exists
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: uninstalscript

- name: Uninstall k3s (server)
  command: /usr/local/bin/k3s-uninstall.sh
  when: uninstalscript.stat.exists

- name: Check if agent uninstall script exists
  stat:
    path: /usr/local/bin/k3s-agent-uninstall.sh
  register: agentuninstalscript

- name: Uninstall k3s (agent)
  command: /usr/local/bin/k3s-agent-uninstall.sh
  when: agentuninstalscript.stat.exists

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent

- name: Check if rc.local exists
  stat:
    path: /etc/rc.local
  register: rcfile

- name: Remove rc.local modifications for proxmox lxc containers
  become: true
  blockinfile:
    path: /etc/rc.local
    content: "{{ lookup('template', 'templates/rc.local.j2') }}"
    create: false
    state: absent
  when: proxmox_lxc_configure and rcfile.stat.exists

- name: Check rc.local for cleanup
  become: true
  slurp:
    src: /etc/rc.local
  register: rcslurp
  when: proxmox_lxc_configure and rcfile.stat.exists

- name: Cleanup rc.local if we only have a Shebang line
  become: true
  file:
    path: /etc/rc.local
    state: absent
  when: proxmox_lxc_configure and rcfile.stat.exists and ((rcslurp.content | b64decode).splitlines() | length) <= 1
